name: CI - Cloud

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set Node version
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm ci
        working-directory: ./cloud/functions
      - name: Setup Firebase CLI (compatible version)
        run: npm install -g firebase-tools@11.30.0
      - name: Deploy to Firebase (with legacy auth)
        run: |
          firebase deploy --only functions --project deckdeckgo-ce04b --token "$FIREBASE_TOKEN"
        working-directory: ./cloud
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
