name: CI - Cloud

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set Node version
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm ci
        working-directory: ./cloud/functions
      - name: Setup Firebase CLI (compatible version)
        run: npm install -g firebase-tools@11.30.0
      - name: Authenticate with Firebase
        run: |
          echo '${{ secrets.FIREBASE_TOKEN }}' > $HOME/gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json
          firebase projects:list
      - name: Deploy to Firebase
        run: |
          echo '${{ secrets.FIREBASE_TOKEN }}' > $HOME/gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json
          firebase use deckdeckgo-ce04b
          firebase deploy --only functions
        working-directory: ./cloud
