name: CI - Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set Node version
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
        working-directory: ./docs
      - name: Build
        run: npm run build
        working-directory: ./docs
      - name: Setup Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        run: |
          echo '${{ secrets.FIREBASE_TOKEN }}' > $HOME/gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json
          firebase deploy --only hosting --project deckdeckgo-ce04b
        working-directory: ./docs
