name: CI - Site

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set Node version
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
        working-directory: ./site
      - name: Build
        run: npm run build
        working-directory: ./site
        env:
          FIREBASE_FEED_TOKEN: ${{ secrets.FIREBASE_FEED_TOKEN }}
          FIREBASE_FUNCTIONS_URL: ${{ secrets.FIREBASE_FUNCTIONS_URL }}
      - name: Setup Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        run: |
          echo '${{ secrets.FIREBASE_TOKEN }}' > $HOME/gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json
          firebase deploy --only hosting --project deckdeckgo-ce04b
        working-directory: ./site
